swagger: "2.0"

info:
  title: "Hello API"
  version: "1.0"

basePath: /v1

paths:
  /product/:
    get:
      operationId: api.product.class_instance.search
      responses:
        '200':
          description: 'List of product'
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'

definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
      price:
        type: integer
        format: int64
